version: 2.1

defaults: &defults
  docker:
      - image: circleci/node:13.8.0

jobs: 
  save_hello_world_output: 
    <<: *defults
    steps:
      - run: echo "Hello world!" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_output:
    <<: *defults
    steps:
      - attach_workspace:
          at: ~/output.txt
      - run: cat ~/output.txt

workflows:
  welcome:
    jobs:
      - save_hello_world_output
      - print_output:
          requires:
            - save_hello_world_output