version: 2.1

defaults: &defults
  docker:
      - image: circleci/node:13.8.0

jobs: 
  print_hello: 
    <<: *defults
    steps:
      - run: echo Hello 

  print_world:
    <<: *defults
    steps:
      - run: echo world!

  print_vals:
    <<: *defults
    steps:
      - run:
          name: "print values"
          command: |
            echo << pipeline.id >>
            echo END!
      - run:
          name: "print env values"
          command: |
            echo ${NAME}


workflows:
  welcome:
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello
      - print_vals:
          requires:
            - print_hello
            - print_world
            